[Spinal][GA] Add CI process for Spinal H7_v2 (#689)

diff --git a/.github/workflows/firmware_build.yml b/.github/workflows/firmware_build.yml
--- a/.github/workflows/firmware_build.yml
+++ b/.github/workflows/firmware_build.yml
@@ -36,6 +36,48 @@ jobs:
       #     source devel/setup.bash
       #   shell: bash
 
+      - name: Build Spinal H7_v2 as STM32CubeIDE project # Build Spinal H7_v2 firmware with STM32CubeIDE
+        shell: bash
+        run: |
+          # set default result to avoid build interruption
+          set +e
+          for i in {1..5}; do
+          echo "=== Attempt #$i for H7_v2 Build ==="
+           #build ros packages related to spinla firmware
+            source /opt/ros/noetic/setup.bash
+            cd ~/catkin_ws
+            catkin config --cmake-args -Dcatkin_DIR=/opt/ros/noetic/share/catkin/cmake
+            catkin build -p 1 -j 1 spinal
+            source devel/setup.bash
+
+            # back to default workspace
+            cd $GITHUB_WORKSPACE
+
+            /opt/st/stm32cubeide_1.8.0/stm32cubeide -nosplash \
+              -application org.eclipse.cdt.managedbuilder.core.headlessbuild \
+              -data ~/STM32CubeIDE/workspace_1.8.0/ \
+              -import aerial_robot_nerve/spinal/mcu_project/boards/stm32H7_v2/STM32CubeIDE/ \
+              -cleanBuild spinal/Debug \
+              -vmargs -Dorg.eclipse.cdt.core.build.parallel=true \
+                      -Dorg.eclipse.cdt.core.build.parallel.threads=12
+            
+            # check build result
+            if [ $? -eq 0 ]; then
+              echo "Build Spinal H7_v2 succeeded on attempt #$i."
+              exit 0  # success
+            else
+              echo "Build Spinal H7_v2 failed on attempt #$i."
+            fi
+          done
+
+          echo "All 5 attempts for Spinal H7_v2 have failed."
+          exit 1
+
+      - name: Clean up STM32CubeIDE # Clean up STM32CubeIDE WS to build same name project
+        shell: bash
+        run: |
+          rm -rf ~/STM32CubeIDE/workspace_1.8.0/.metadata
+          
       - name: Build Spinal H7 as STM32CubeIDE project # Build Spinal H7 firmware with STM32CubeIDE
         shell: bash
         run: |
@@ -122,6 +164,12 @@ jobs:
             -cleanBuild neuron/Debug \
             -vmargs -Dorg.eclipse.cdt.core.build.parallel=true \
             -Dorg.eclipse.cdt.core.build.parallel.threads=12
+
+      - name: Upload Spinal H7_v2 artifacts # Upload required Spinal H7 files for flash.
+        uses: actions/upload-artifact@v4
+        with:
+          name: SpinalH7_v2.artifacts
+          path: aerial_robot_nerve/spinal/mcu_project/boards/stm32H7_v2/STM32CubeIDE/Debug/spinal.*            
 
       - name: Upload Spinal H7 artifacts # Upload required Spinal H7 files for flash.
         uses: actions/upload-artifact@v4
